### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by Nerodacles** [AplhaSlayer1964/kemono-dl#43]
### Version
Version: 2021.12.29.01

### Your Command
```bash

--dateafter 20210101

```

### Description of bug
Always crashing.

### How To Reproduce
add `--dateafter 20210101` 

### Error messages and tracebacks
```python
Traceback (most recent call last):
  File ".\kemono-dl\kemono-dl.py", line 4, in <module>
    main()
  File ".\kemono-dl\src\main.py", line 608, in main
    D.download_posts()
  File ".\kemono-dl\src\main.py", line 164, in download_posts
    if self._should_download():
  File ".\kemono-dl\src\main.py", line 233, in _should_download
    elif not(self.current_post['date_object'] == args['date'] or self.current_post['date_object'] <= args['datebefore'] or self.current_post['date_object'] >= args['dateafter']):
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.datetime'
```
 

[debug.log](https://github.com/AplhaSlayer1964/kemono-dl/files/7791268/debug.log)

**Comment by AplhaSlayer1964** [comment]
Can you post the service and user_id?

**Comment by Nerodacles** [comment]
`python kemono-dl.py --retry-download 1 --cookies "cookie-kemono.txt,cookie-coomer.txt" -o ".\Kemono\raw" --archive ".\raw\archive.txt" --kemono-favorite-users --coomer-favorite-users --save-banner --save-icon --max-filesize 100MB --restrict-names`

**Comment by Nerodacles** [comment]
Oh, maybe is because kemono is deduping the site..

**Comment by Nerodacles** [comment]
OK, when i put the next lines on `main.py`

```
logger.info(self.current_post['date_object'])
logger.info(args['datebefore'])
```

on that post it always shows:

1rst logger = INFO: None
2nd logger = INFO: 0001-01-01 00:00:00


Dont know whats happening, and dont know why "datebefore" is on 0001, bc i put 20210101

**Comment by Nerodacles** [comment]
Maybe put in the code if a post dont have a date, it always skips it?

**Comment by AplhaSlayer1964** [comment]
> Maybe put in the code if a post dont have a date, it always skips it?

So the thing is the should never not have a published date. I check the post where your log file stopped and the api call for the post has a published date. Also if there is no published date it should return datetime.datetime.min

**Comment by AplhaSlayer1964** [comment]
could you add
```python
logger.info(post['published'])
```
at the start of the get_post_date(post:dict) function and report what it prints on the last call before it crashes?

**Comment by Nerodacles** [comment]
WTFFFF, it just works now!, it could be because kemono was deduping the site??

**Comment by Nerodacles** [comment]
Im doing some test, before closing this issue.

**Comment by AplhaSlayer1964** [comment]
> WTFFFF, it just works now!, it could be because kemono was deduping the site??

So that shouldn't be the problem. Why I'm confused is because there is no way that could be set to None unless somehow the json didn't load from the site but because I'm using requests .json function it should have crashed at that if anything.

**Comment by Nerodacles** [comment]
Nope, still crashes

**Comment by AplhaSlayer1964** [comment]
can you replace the function around 520 ish in main.py with this code:
```python
def get_post_date(post:dict):
    logger.info(f"This is what the post json says for published: {post['published']}")
    if post['published']:
        date_object = datetime.datetime.strptime(post['published'], r'%a, %d %b %Y %H:%M:%S %Z')
        date_string = date_object.strftime(r'%Y%m%d')
    else:
        date_object = datetime.datetime.min
        date_string = '00000000'
    if date_object == None:
        print('WTF')
        for key, value in post.items():
            print(f"{key} : {value}")
        quit()
    return (date_object, date_string)
```

**Comment by Nerodacles** [comment]
Same thing:

```
INFO: This is what the post json says for published: Thu, 04 Jun 2020 23:14:17 GMT
INFO: This is what the post json says for published: Wed, 03 Jun 2020 15:20:47 GMT
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: None
INFO: This is what the post json says for published: Wed, 10 Mar 2021 20:54:53 GMT
```

**Comment by Nerodacles** [comment]
> can you replace the function around 520 ish in main.py with this code:
> 
> ```python
> def get_post_date(post:dict):
>     logger.info(f"This is what the post json says for published: {post['published']}")
>     if post['published']:
>         date_object = datetime.datetime.strptime(post['published'], r'%a, %d %b %Y %H:%M:%S %Z')
>         date_string = date_object.strftime(r'%Y%m%d')
>     else:
>         date_object = datetime.datetime.min
>         date_string = '00000000'
>     if date_object == None:
>         print('WTF')
>         for key, value in post.items():
>             print(f"{key} : {value}")
>         quit()
>     return (date_object, date_string)
> ```

I know, i was just checking other things

**Comment by AplhaSlayer1964** [comment]
can you send me the post link for one of the ones that say None

**Comment by Nerodacles** [comment]
Ok, it will take a min

**Comment by AplhaSlayer1964** [comment]
In that new function I have it print out the post json because I think somehow it's not getting the correct json information.

**Comment by Nerodacles** [comment]
Hmm, with this link: `https://kemono.party/fantia/user/83679` it always crash

```
INFO: Gathering posts
INFO: This is what the post json says for published: Sat, 25 Dec 2021 18:13:52 GMT
INFO: This is what the post json says for published: Sun, 19 Dec 2021 22:13:37 GMT
INFO: This is what the post json says for published: Fri, 17 Dec 2021 22:23:56 GMT
INFO: This is what the post json says for published: Sun, 05 Dec 2021 10:46:38 GMT
INFO: This is what the post json says for published: Sun, 28 Nov 2021 03:38:42 GMT
INFO: This is what the post json says for published: Fri, 26 Nov 2021 19:32:41 GMT
INFO: This is what the post json says for published: Tue, 23 Nov 2021 20:37:53 GMT
INFO: This is what the post json says for published: Mon, 22 Nov 2021 11:20:25 GMT
INFO: This is what the post json says for published: Sun, 31 Oct 2021 18:36:33 GMT
INFO: This is what the post json says for published: Fri, 29 Oct 2021 20:43:03 GMT
INFO: This is what the post json says for published: Mon, 25 Oct 2021 18:39:31 GMT
INFO: This is what the post json says for published: Wed, 06 Oct 2021 12:52:35 GMT
INFO: This is what the post json says for published: Thu, 30 Sep 2021 12:13:45 GMT
INFO: This is what the post json says for published: Fri, 24 Sep 2021 21:00:00 GMT
INFO: This is what the post json says for published: Tue, 21 Sep 2021 18:00:00 GMT
INFO: This is what the post json says for published: Mon, 20 Sep 2021 22:52:25 GMT
INFO: This is what the post json says for published: Tue, 31 Aug 2021 07:27:47 GMT
INFO: This is what the post json says for published: Sun, 29 Aug 2021 19:45:06 GMT
INFO: This is what the post json says for published: Tue, 17 Aug 2021 14:29:44 GMT
INFO: This is what the post json says for published: Sat, 14 Aug 2021 23:13:31 GMT
INFO: This is what the post json says for published: Sun, 25 Jul 2021 19:48:16 GMT
INFO: This is what the post json says for published: Fri, 23 Jul 2021 18:56:08 GMT
INFO: This is what the post json says for published: Thu, 22 Jul 2021 21:40:49 GMT
INFO: This is what the post json says for published: Wed, 30 Jun 2021 12:52:04 GMT
INFO: This is what the post json says for published: Sun, 20 Jun 2021 21:04:20 GMT
INFO: This is what the post json says for published: Thu, 17 Jun 2021 18:00:00 GMT
INFO: This is what the post json says for published: Wed, 09 Jun 2021 19:51:41 GMT
INFO: This is what the post json says for published: Sat, 29 May 2021 21:01:34 GMT
INFO: This is what the post json says for published: Fri, 28 May 2021 19:24:14 GMT
INFO: This is what the post json says for published: Fri, 21 May 2021 19:55:23 GMT
INFO: This is what the post json says for published: Sat, 15 May 2021 19:08:35 GMT
INFO: This is what the post json says for published: Fri, 30 Apr 2021 17:50:00 GMT
INFO: This is what the post json says for published: Mon, 26 Apr 2021 11:43:36 GMT
INFO: This is what the post json says for published: Wed, 14 Apr 2021 20:00:00 GMT
INFO: This is what the post json says for published: Thu, 01 Apr 2021 17:44:07 GMT
INFO: This is what the post json says for published: Tue, 30 Mar 2021 21:26:53 GMT
INFO: This is what the post json says for published: Sat, 27 Mar 2021 13:33:39 GMT
INFO: This is what the post json says for published: Tue, 09 Mar 2021 23:18:21 GMT
INFO: This is what the post json says for published: Wed, 03 Mar 2021 22:24:45 GMT
INFO: This is what the post json says for published: Sat, 27 Feb 2021 13:10:14 GMT
INFO: This is what the post json says for published: Thu, 11 Feb 2021 22:38:00 GMT
INFO: This is what the post json says for published: Sun, 31 Jan 2021 16:14:48 GMT
INFO: This is what the post json says for published: Fri, 01 Jan 2021 19:06:57 GMT
INFO: This is what the post json says for published: Thu, 31 Dec 2020 16:41:00 GMT
INFO: This is what the post json says for published: Mon, 07 Dec 2020 10:58:23 GMT
INFO: This is what the post json says for published: Sun, 06 Dec 2020 03:12:35 GMT
INFO: This is what the post json says for published: Fri, 04 Dec 2020 17:47:35 GMT
INFO: This is what the post json says for published: Thu, 26 Nov 2020 20:22:38 GMT
INFO: This is what the post json says for published: Wed, 25 Nov 2020 16:10:40 GMT
INFO: This is what the post json says for published: Mon, 02 Nov 2020 13:11:36 GMT
INFO: This is what the post json says for published: Thu, 15 Oct 2020 22:31:26 GMT
INFO: This is what the post json says for published: Sun, 11 Oct 2020 15:20:00 GMT
INFO: This is what the post json says for published: Sat, 10 Oct 2020 21:08:53 GMT
INFO: This is what the post json says for published: Fri, 09 Oct 2020 21:53:00 GMT
INFO: User: 日南(Canan)
INFO: Post: Merry_Christmas__
INFO: Skipping Post: Post Archived
INFO: Post: Merry_Christmas__
INFO: Skipping Post: Post Archived
INFO: Post: _______________
INFO: Skipping Post: Post Archived
INFO: Post: _______________
INFO: Skipping Post: Post Archived
INFO: Post: _________________
INFO: Skipping Post: Post Archived
INFO: Post: _________________
INFO: Skipping Post: Post Archived
INFO: Post: _____________________________
INFO: Skipping Post: Post Archived
INFO: Post: _____________________________
INFO: Skipping Post: Post Archived
INFO: Post: L________________(______________)
INFO: Skipping Post: Post Archived
INFO: Post: L________________(______________)
INFO: Skipping Post: Post Archived
INFO: Post: ________________________
INFO: Skipping Post: Post Archived
INFO: Post: ________________________
INFO: Skipping Post: Post Archived
INFO: Post: _____________________
INFO: Downloading [01]_02ea54e7-bf6a-4a2a-a13a-fe5259839e8e.jpg
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [02]_ce317364-0dcf-4277-b720-9927fdd57e9a.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [03]_b6515379-12b4-4903-bb77-34613f5e131b.png
WARNING: Resuming download: File on disk does not match hash
ERROR: 416 Requested Range Not Satisfiable: Will always happen if server hash is wrong! Please check file and report to site owner that file hash might be wrong
INFO: Downloading [04]_31de672a-dc1a-4cdb-b80e-a5ba89c84e56.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [05]_3db6eb50-36e7-4031-b044-1aab571b125c.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [06]_0d25fffd-1e96-4fb8-87e5-2f5c5249472b.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [07]_188d27b4-656e-4f3c-9769-295c15dc0aa2.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [08]_9ed6095b-0f00-4d23-937b-8075204e5fe1.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [09]_21427075-e005-4adc-bc60-ad0f7051aad6.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [10]_30aa69e1-4f5a-4701-8a01-294aae89450c.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [11]_8e862704-75a3-492d-a89e-947104535721.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [12]_c0e27b85-8581-4a46-8cf4-95541081eb3b.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [13]_f37fb3ea-8241-4f98-9ab3-f257d32ad99a.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [14]_f46d280c-88ec-42cd-8e8c-190807502d2d.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [15]_463bf017-b660-46da-816a-fade1fabe326.png
INFO: Skipping download: File on disk has matching hash
INFO: Downloading [16]_Canan_________Fantia.zip
INFO: Skipping download: File on disk has matching hash
INFO: Post: _____________________
Traceback (most recent call last):
  File "kemono-dl\kemono-dl.py", line 4, in <module>
    main()
  File "kemono-dl\src\main.py", line 617, in main
    D.download_posts()
  File "kemono-dl\src\main.py", line 164, in download_posts
    if self._should_download():
  File "kemono-dl\src\main.py", line 234, in _should_download
    elif not(self.current_post['date_object'] == args['date'] or self.current_post['date_object'] <= args['datebefore'] or self.current_post['date_object'] >= args['dateafter']):
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.datetime'

**Comment by Nerodacles** [comment]
And i have the new function on main

**Comment by AplhaSlayer1964** [comment]
ok give me a second to think of another place to have that check since they all passed somehow.

**Comment by AplhaSlayer1964** [comment]
ok so on around line 230ish on main.py before the comment `# check if post date is in range` place this:
```python
        if self.current_post['date_object'] == None:
            print('WTF')
            for key, value in self.current_post.items():
                print(f"{key} : {value}")
            quit()

        # check if post date is in range
```

**Comment by Nerodacles** [comment]
After: 
```Python 
if not self._is_update_newer(self.current_post['edited'], data['edited']):
```
?

**Comment by AplhaSlayer1964** [comment]
sorry my version is a bit off. Should be after the archive check
```python
        # check archive fle
        if args['archive']:
            if os.path.exists(args['archive']):
                with open(args['archive'],'r') as f:
                    archived = f.read().splitlines()
                if '/{service}/user/{user}/post/{id}'.format(**self.current_post) in archived:
                    logger.info("Skipping Post: Post Archived")
                    return False
```

**Comment by Nerodacles** [comment]
No it was my bad, but let me try. XD

**Comment by Nerodacles** [comment]
```
2021-12-30 03:18:23,771:INFO: WTF
2021-12-30 03:18:23,771:INFO: added : Wed, 24 Nov 2021 19:09:24 GMT
2021-12-30 03:18:23,771:INFO: attachments : [{'name': '02ea54e7-bf6a-4a2a-a13a-fe5259839e8e.jpg', 'path': '/ae/44/ae440c7ea0b2c4932ec390e9b097a88e82d88526909ee262a7f81842d5d11769.jpg'}, {'name': 'ce317364-0dcf-4277-b720-9927fdd57e9a.png', 'path': '/48/6b/486b07a085420c779074f86ffc731521c32468610ea5eadc16d0e234fccf96ad.png'}, {'name': 'b6515379-12b4-4903-bb77-34613f5e131b.png', 'path': '/d4/06/d40618d2a7d10266d3f9af96e8a4403f82620934b6f37b41afa7fd7cf6b52f4e.png'}, {'name': '31de672a-dc1a-4cdb-b80e-a5ba89c84e56.png', 'path': '/6e/1b/6e1b032d09381d27181ceed3923fd6ca2b27750fe0838de110a70ab59a22d614.png'}, {'name': '3db6eb50-36e7-4031-b044-1aab571b125c.png', 'path': '/0c/15/0c15f308edd4c24a5ca9796f9375965d84b1d5003a89fef177e9b1a4b6dbf53a.png'}, {'name': '0d25fffd-1e96-4fb8-87e5-2f5c5249472b.png', 'path': '/b2/dc/b2dc5bdbdb1bdfc09267adcf30d55fa99fb81687892b45728f88da33d95cf114.png'}, {'name': '188d27b4-656e-4f3c-9769-295c15dc0aa2.png', 'path': '/1e/16/1e16d42a8c3230f06d2fda4e092f417ae694b52de619660c51b08cee25d45640.png'}, {'name': '9ed6095b-0f00-4d23-937b-8075204e5fe1.png', 'path': '/3e/91/3e918027c7a9f324de1093b2fe4efaf381e07b3ae4fdf7c0709185b7056d0d8b.png'}, {'name': '21427075-e005-4adc-bc60-ad0f7051aad6.png', 'path': '/d8/74/d874b9b33bb7ef726102a96a9497cc0942a113685f203b93fb52bc2948500134.png'}, {'name': '30aa69e1-4f5a-4701-8a01-294aae89450c.png', 'path': '/30/53/3053baaa619846567f30ea3a08eb5d9597756a233eccd03391b6e69b739345f1.png'}, {'name': '8e862704-75a3-492d-a89e-947104535721.png', 'path': '/fa/d8/fad835e232355aa23ea821e261cfea933ab92b33e800e1046516588312231386.png'}, {'name': 'c0e27b85-8581-4a46-8cf4-95541081eb3b.png', 'path': '/13/ca/13ca1e2c29f4379a1fe304ee0917c524bca3afbf68026c68758dc6c08288cbbf.png'}, {'name': 'f37fb3ea-8241-4f98-9ab3-f257d32ad99a.png', 'path': '/5b/10/5b10ac712131d409e96ccbce49d23ceb580eff5d49f609d131ea0b32b891c390.png'}, {'name': 'f46d280c-88ec-42cd-8e8c-190807502d2d.png', 'path': '/33/68/336843b72c1695a8b0d7d01cb0f262dec8ef68d1f1f622e35b74054752c18cbf.png'}, {'name': '463bf017-b660-46da-816a-fade1fabe326.png', 'path': '/82/4b/824b2be628b6bc2d16b2d2f238050d21e912593e7f23acdd6b348b0dd98e70f4.png'}, {'name': 'Canan日南_キョンシー_Fantia.zip', 'path': '/59/cb/59cbb7c40fbf1b6cfa345a46009aac0d4fc066a107f638593cbe3c26535171b6.zip'}]
2021-12-30 03:18:23,772:INFO: content : 🍒上(↑)の「⭐️お気に入り」を押して頂けると次の投稿のモチベがあがります！
text here its just too long

2021-12-30 03:18:23,773:INFO: edited : None
2021-12-30 03:18:23,773:INFO: embed : {}
2021-12-30 03:18:23,774:INFO: file : {'name': '02ea54e7-bf6a-4a2a-a13a-fe5259839e8e.jpg', 'path': '/ae/44/ae440c7ea0b2c4932ec390e9b097a88e82d88526909ee262a7f81842d5d11769.jpg'}
2021-12-30 03:18:23,774:INFO: id : 999697
2021-12-30 03:18:23,774:INFO: published : Tue, 23 Nov 2021 20:37:53 GMT
2021-12-30 03:18:23,774:INFO: service : fantia
2021-12-30 03:18:23,774:INFO: shared_file : False
2021-12-30 03:18:23,775:INFO: title : 大好評だったむちむちキョンシーの自撮り集💕
2021-12-30 03:18:23,775:INFO: user : 83679
2021-12-30 03:18:23,775:INFO: date_object : None
2021-12-30 03:18:23,775:INFO: date_object_string : 20211123
```

**Comment by Nerodacles** [comment]
`date_object = None` but `date_object_string : 20211123`.

WTFFF

**Comment by AplhaSlayer1964** [comment]
ok so around line 178ish there is this command `self.current_post['date_object'] = None` change it to something like `self.current_post['date_object'] = "111111"` and for that if statement I told you to add have it check for "111111" instead of None.  The None that is written there should be overwritten by the next posts but just for sanity check.

**Comment by AplhaSlayer1964** [comment]
When I run the script on that fanita link you sent I still don't get this problem.

**Comment by AplhaSlayer1964** [comment]
what version of python are you using?

**Comment by Nerodacles** [comment]
Using Python 3.10.0

**Comment by Nerodacles** [comment]
That line is exactly causing the problem.

**Comment by Nerodacles** [comment]
```Python
self.current_post['date_object'] = "111111"
```


In this post:
```
user_id: 83679 service: fantia post_id: 999697 url: https://kemono.party/fantia/user/83679/post/999697
WTF
added : Wed, 24 Nov 2021 19:09:24 GMT
attachments : [{'name': '02ea54e7-bf6a-4a2a-a13a-fe5259839e8e.jpg', 'path': '/ae/44/ae440c7ea0b2c4932ec390e9b097a88e82d88526909ee262a7f81842d5d11769.jpg'}, {'name': 'ce317364-0dcf-4277-b720-9927fdd57e9a.png', 'path': '/48/6b/486b07a085420c779074f86ffc731521c32468610ea5eadc16d0e234fccf96ad.png'}, {'name': 'b6515379-12b4-4903-bb77-34613f5e131b.png', 'path': '/d4/06/d40618d2a7d10266d3f9af96e8a4403f82620934b6f37b41afa7fd7cf6b52f4e.png'}, {'name': '31de672a-dc1a-4cdb-b80e-a5ba89c84e56.png', 'path': '/6e/1b/6e1b032d09381d27181ceed3923fd6ca2b27750fe0838de110a70ab59a22d614.png'}, {'name': '3db6eb50-36e7-4031-b044-1aab571b125c.png', 'path': '/0c/15/0c15f308edd4c24a5ca9796f9375965d84b1d5003a89fef177e9b1a4b6dbf53a.png'}, {'name': '0d25fffd-1e96-4fb8-87e5-2f5c5249472b.png', 'path': '/b2/dc/b2dc5bdbdb1bdfc09267adcf30d55fa99fb81687892b45728f88da33d95cf114.png'}, {'name': '188d27b4-656e-4f3c-9769-295c15dc0aa2.png', 'path': '/1e/16/1e16d42a8c3230f06d2fda4e092f417ae694b52de619660c51b08cee25d45640.png'}, {'name': '9ed6095b-0f00-4d23-937b-8075204e5fe1.png', 'path': '/3e/91/3e918027c7a9f324de1093b2fe4efaf381e07b3ae4fdf7c0709185b7056d0d8b.png'}, {'name': '21427075-e005-4adc-bc60-ad0f7051aad6.png', 'path': '/d8/74/d874b9b33bb7ef726102a96a9497cc0942a113685f203b93fb52bc2948500134.png'}, {'name': '30aa69e1-4f5a-4701-8a01-294aae89450c.png', 'path': '/30/53/3053baaa619846567f30ea3a08eb5d9597756a233eccd03391b6e69b739345f1.png'}, {'name': '8e862704-75a3-492d-a89e-947104535721.png', 'path': '/fa/d8/fad835e232355aa23ea821e261cfea933ab92b33e800e1046516588312231386.png'}, {'name': 'c0e27b85-8581-4a46-8cf4-95541081eb3b.png', 'path': '/13/ca/13ca1e2c29f4379a1fe304ee0917c524bca3afbf68026c68758dc6c08288cbbf.png'}, {'name': 'f37fb3ea-8241-4f98-9ab3-f257d32ad99a.png', 'path': '/5b/10/5b10ac712131d409e96ccbce49d23ceb580eff5d49f609d131ea0b32b891c390.png'}, {'name': 'f46d280c-88ec-42cd-8e8c-190807502d2d.png', 'path': '/33/68/336843b72c1695a8b0d7d01cb0f262dec8ef68d1f1f622e35b74054752c18cbf.png'}, {'name': '463bf017-b660-46da-816a-fade1fabe326.png', 'path': '/82/4b/824b2be628b6bc2d16b2d2f238050d21e912593e7f23acdd6b348b0dd98e70f4.png'}, {'name': 'Canan日南_キョンシー_Fantia.zip', 'path': '/59/cb/59cbb7c40fbf1b6cfa345a46009aac0d4fc066a107f638593cbe3c26535171b6.zip'}]
content : 🍒上(↑)の「⭐️お気に入り」を押して頂けると次の投稿のモチベがあがります！

edited : None
embed : {}
file : {'name': '02ea54e7-bf6a-4a2a-a13a-fe5259839e8e.jpg', 'path': '/ae/44/ae440c7ea0b2c4932ec390e9b097a88e82d88526909ee262a7f81842d5d11769.jpg'}
id : 999697
published : Tue, 23 Nov 2021 20:37:53 GMT
service : fantia
shared_file : False
title : 大好評だったむちむちキョンシーの自撮り集💕
user : 83679
date_object : 111111
date_object_string : 20211123
```

**Comment by AplhaSlayer1964** [comment]
Yep I just noticed another problem that was causing that line to be an issue. Can you remove these two lines 118 and 119:
```python
                if post not in self.download_list:
                    new_user['posts'].append(post)
```
And reset the 11111 to None.

**Comment by AplhaSlayer1964** [comment]
So I noticed that posts were trying to be downloaded twice but for some reason on yours the dictionaries stayed linked. Those lines should not be there.

**Comment by Nerodacles** [comment]
NIICEEE, it works now! Tnx. <3

**Comment by Nerodacles** [comment]
And the lines actually were 120 and 121

**Comment by AplhaSlayer1964** [comment]
ok I will be pushing a new release. I should probably do more testing before I publish stuff.
