### ISSUE TITLE
SSLError&VPN related

### ISSUE THREAD

**Issue by KerwinRae** [AplhaSlayer1964/kemono-dl#53]
### Version

Version:2022.01.29

### Your Command

```bash

python kemono-dl.py --cookies cookie.txt --links https://kemono.party/fanbox/user/56572917

```

### Description of bug

I can't use VPN to download through the script. However it works through Browsers.
[debug.log](https://github.com/AplhaSlayer1964/kemono-dl/files/8013327/debug.log)

### How To Reproduce

Use Vpn

### Error messages and tracebacks

```python

Traceback (most recent call last):
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "D:\Python\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Python\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\Python\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Python\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Python\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1122)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\Python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/AplhaSlayer1964/kemono-dl/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\ASUS\Downloads\kemono-dl-2022.01.29\kemono-dl.py", line 4, in <module>
    main()
  File "G:\ASUS\Downloads\kemono-dl-2022.01.29\src\main.py", line 738, in main
    check_version()
  File "G:\ASUS\Downloads\kemono-dl-2022.01.29\src\main.py", line 723, in check_version
    responce = requests.get(url=github_api_url, timeout=TIMEOUT)
  File "D:\Python\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/AplhaSlayer1964/kemono-dl/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))

```

### Additional comments

I don't know code stuff,but I guess maybe the problem is with the github's api?
Never mind, I'm a total layman

**Comment by AplhaSlayer1964** [comment]
It seems to be crashing when checking for updates. Very weird. I will have to look more tomorrow. For now you could go comment out the function that checks GitHub for the newest version in main.py in the main function at the bottom.

**Comment by AplhaSlayer1964** [comment]
Do you mind telling me what vpn you use? Also can you visit this, https://api.github.com/repos/AplhaSlayer1964/kemono-dl/releases/latest, site on your browser?

**Comment by KerwinRae** [comment]
Here‘s one of the VPN services I use. It's about to expire soon, and there's not much traffic left. So maybe it can only be used for a little testing
Link for V2RAY: https://ubisoft.cyou/link/vIfiatuG64Iob62g?sub=3&extend=1
And I can visit the site though the page just shows many lines of code.
[web content.txt](https://github.com/AplhaSlayer1964/kemono-dl/files/8021411/web.content.txt)
.

**Comment by AplhaSlayer1964** [comment]
What you see when going to the site is correct. So it is very weird that the program can't access it over the vpn. I use PIA vpn and have never had an issue. I don't know if this vpn uses something different from openvpn or wiregaurd so that might cause the issue. I will push a new update that that does better catching when checking for updates so the program will still continue even if it can't check for updates.

**Comment by KerwinRae** [comment]
Thank you for your excellent work that making it easy for us to download a huge amount of content!
