### ISSUE TITLE
When youtube link in post which has been scaned, this shell dont work.

### ISSUE THREAD

**Issue by fwsouls** [AplhaSlayer1964/kemono-dl#60]
![屏幕截图 2022-02-16 165107](https://user-images.githubusercontent.com/99174336/154228876-e8ee88be-f6fc-4adb-a5ca-c51a96980fa3.png)
post link:https://kemono.party/patreon/user/192923/post/58498986

**Comment by fwsouls** [comment]
`Traceback (most recent call last):
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\kemono-dl.py", line 4, in <module>
    main()
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 765, in main
    downloader(urls)
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 68, in __init__
    self.add_links()
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 120, in add_links
    self._parse_links(url)
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 128, in _parse_links
    self._find_posts(user.group(1),user.group(2),user.group(3))
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 176, in _find_posts
    self.download_post()
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 188, in download_post
    self._download_attachments()
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 324, in _download_attachments
    self._requests_download(file_url, file_name, file_hash)
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 562, in _requests_download
    with open(file_name, 'ab') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Microsoft\\Desktop\\kemono-dl-2022.02.10\\Downloads\\patreon\\zetaharu [192923]\\[2
0211109] [58503013] Attack on Titan Speedpaint\\[1]_https___www.patreon.com_media-u_Z0FBQUFBQmlCbGs1SXFpZFRGOGlXNERhUnhGQjNBOEx5RHk3OWRUNFl0WXFVY0VwOC1
WQzZyVDZxY0p6OXVybzkwak1FOFRueHFITmtpNzU3VjdybTZKcjR4S3dRcTE3QlFuam9uU2ljbG5rVy1BRnlnN1J0MHpHdl9NUS1PYU1SbHl3N2JyZ0oyZmc3Z0FsdXNCOWFZVFFCVndEMW1iZi1.jp
g'`

**Comment by fwsouls** [comment]
`Traceback (most recent call last):
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\kemono-dl.py", line 4, in <module>
    main()
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 765, in main
    downloader(urls)
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 68, in __init__
    self.add_links()
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 120, in add_links
    self._parse_links(url)
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 128, in _parse_links
    self._find_posts(user.group(1),user.group(2),user.group(3))
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 176, in _find_posts
    self.download_post()
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 188, in download_post
    self._download_attachments()
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 324, in _download_attachments
    self._requests_download(file_url, file_name, file_hash)
  File "C:\Users\Microsoft\Desktop\kemono-dl-2022.02.10\src\main.py", line 562, in _requests_download
    with open(file_name, 'ab') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Microsoft\\Desktop\\kemono-dl-2022.02.10\\Downloads\\patreon\\zetaharu [192923]\\[20211109] [58503013] Attack on Titan Speedpaint\\[1]_https___www.patreon.com_mediau_Z0FBQUFBQmlCbGs1SXFpZFRGOGlXNERhUnhGQjNBOEx5RHk3OWRUNFl0WXFVY0VwOC1WQzZyVDZxY0p6OXVybzkwak1FOFRueHFITmtpNzU3VjdybTZKcjR4S3dRcTE3QlFuam9uU2ljbG5rVy1BRnlnN1J0MHpHdl9NUS1PYU1SbHl3N2JyZ0oyZmc3Z0FsdXNCOWFZVFFCVndEMW1iZi1.jpg'`

**Comment by fwsouls** [comment]
![屏幕截图 2022-02-16 170441](https://user-images.githubusercontent.com/99174336/154231273-39f8f6e9-42ee-4aad-8dc5-252dc9106e0c.png)

**Comment by AplhaSlayer1964** [comment]
Open a new bug report using the bug report template and fill everything out.

**Comment by AplhaSlayer1964** [comment]
Also looks like the problem is you didn't disable path length limit when installing python.
