### ISSUE TITLE
[WinError 32] file deleting error

### ISSUE THREAD

**Issue by neuromememachine** [AplhaSlayer1964/kemono-dl#7]
Version: kemono-dl 2021.10.10

Service: Patreon
User id: 4623730

My command and error which I got

```
Microsoft Windows [Version 10.0.19042.928]
(c) Microsoft Corporation. All rights reserved.

C:\Users\USER>cd C:\Users\USER\Desktop\kemono-dl

C:\Users\USER\Desktop\kemono-dl>python kemono-dl.py -i --cookies "cookies.txt" -f users.txt -a archive.txt
Downloading: fireboxstudio [4623730] icon
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\kemono-dl\kemono-dl.py", line 273, in get_pfp_banner
    os.remove(os.path.join(folder_path, file_name))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USER\\Desktop\\kemono-dl\\Downloads\\patreon\\fireboxstudio [4623730]\\fireboxstudio [4623730] icon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\kemono-dl\kemono-dl.py", line 334, in <module>
    main()
  File "C:\Users\USER\Desktop\kemono-dl\kemono-dl.py", line 330, in main
    if not extract_link(link.strip()):
  File "C:\Users\USER\Desktop\kemono-dl\kemono-dl.py", line 309, in extract_link
    get_pfp_banner(info)
  File "C:\Users\USER\Desktop\kemono-dl\kemono-dl.py", line 275, in get_pfp_banner
    os.remove(os.path.join(folder_path, file_name)) # site might return garbage data if no icon or banner is found
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USER\\Desktop\\kemono-dl\\Downloads\\patreon\\fireboxstudio [4623730]\\fireboxstudio [4623730] icon'


```

https://stackoverflow.com/questions/27215462/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is

It seems to be a bug in the part that deletes the file when the site returns garbage data, and I checked on Stackoverflow and found that it is necessary to close the file before deleting it. I took a look at the code, but I don't think I can fix it.ｓ

**Comment by AplhaSlayer1964** [comment]
This was fixed in 2021.10.11
