### ISSUE TITLE
Archive file error

### ISSUE THREAD

**Issue by A-Random-Mf** [AplhaSlayer1964/kemono-dl#74]
DEBUG: Given command: python kemono-dl.py --cookies coomer.party_cookies.txt --links https://coomer.party/onlyfans/user/kalgirl_up --output /Downloads/{service}/{username}/{published}-{id}.{ext} --skip-filetypes jpg,png -a downloaded.txt --verbose
DEBUG: User API URL: https://coomer.party/api/onlyfans/user/kalgirl_up?o=0
Traceback (most recent call last):
  File "/home/user/test/kemono-dl/kemono-dl.py", line 4, in <module>  main()
File "/home/user/test/kemono-dl/src/main.py", line 807, in main
  downloader(urls)
  File "/home/user/test/kemono-dl/src/main.py", line 68, in __init__  self.add_links()
File "/home/user/test/kemono-dl/src/main.py", line 109, in add_links  
  self.parse_links(url)
File "/home/user/test/kemono-dl/src/main.py", line 116, in parse_links
self.get_posts(site=user.group(1),service=user.group(2),user_id=user.group(3))
File "/home/user/test/kemono-dl/src/main.py", line 162, in get_posts  
  self.download_post()
File "/home/user/test/kemono-dl/src/main.py", line 231, in download_post
  if self.should_download_post():
File "/home/user/test/kemono-dl/src/main.py", line 250, in should_download_post
  return self.check_archived()
File "/home/user/test/kemono-dl/src/main.py", line 279, in check_archived
if '/{service}/user/{user}/post/{id}'.format(**self.current_post) in archived:
KeyError: 'user'

**Comment by AplhaSlayer1964** [comment]
Yes the --archive is broken in the pre release but if you download the master it should be fixed. Will push a new release this weekend that fixes this.

**Comment by A-Random-Mf** [comment]
Thanks. Appreciate it
