### ISSUE TITLE
Script crashes with -fav-users option

### ISSUE THREAD

**Issue by sybarix** [AplhaSlayer1964/kemono-dl#86]
### Version
Version: 2022.04.24

### Your Command
```bash

@echo off
py kemono-dl.py --cookies "kemono.party_cookies.txt,coomer.party_cookies.txt" --skip-filetypes PSD --inline --json --extract-links --yt-dlp --kemono-fav-users all --coomer-fav-users all --dirname-pattern "D:\Storage\Offline\Images\Archivers\DL\{username} [{user_id}] {service}" --filename-pattern "({published}) {title} {index} - {filename} [{id}].{ext}" --date-strf-pattern "%%y%%m%%d" --verbose
pause

```

### Description of bug
The script fails when any of the --kemono/coomer-fav-users all/service options are used. It works when specifying a specific link via --links.

### How To Reproduce
Run the script with --kemono-fav-users all, --kemono-fav-users fanbox, --coomer-fav-users all, etc

### Error messages and tracebacks
```python

DEBUG:Getting creator json from https://kemono.party/api/creators/
DEBUG:Getting creator json from https://coomer.party/api/creators/
DEBUG:Getting favorite json from https://kemono/api/favorites?type=artist
ERROR:Unable to get favorite users from kemono.party
Traceback (most recent call last):
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002336FE56170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kemono', port=443): Max retries exceeded with url: /api/favorites?type=artist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002336FE56170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Storage\Offline\Images\Archivers\kemono-dl-2022.04.24\src\main.py", line 627, in start_download
    self.get_favorites('kemono', 'artist', self.k_fav_users)
  File "D:\Storage\Offline\Images\Archivers\kemono-dl-2022.04.24\src\main.py", line 113, in get_favorites
    response = self.session.get(url=fav_api, headers=self.headers, cookies=self.cookies, timeout=self.timeout)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='kemono', port=443): Max retries exceeded with url: /api/favorites?type=artist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002336FE56170>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
DEBUG:Getting favorite json from https://coomer/api/favorites?type=artist
ERROR:Unable to get favorite users from coomer.party
Traceback (most recent call last):
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002336FFB4550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coomer', port=443): Max retries exceeded with url: /api/favorites?type=artist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002336FFB4550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Storage\Offline\Images\Archivers\kemono-dl-2022.04.24\src\main.py", line 632, in start_download
    self.get_favorites('coomer', 'artist', self.c_fav_users)
  File "D:\Storage\Offline\Images\Archivers\kemono-dl-2022.04.24\src\main.py", line 113, in get_favorites
    response = self.session.get(url=fav_api, headers=self.headers, cookies=self.cookies, timeout=self.timeout)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\BC\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='coomer', port=443): Max retries exceeded with url: /api/favorites?type=artist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002336FFB4550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Press any key to continue . . .

```

**Comment by AplhaSlayer1964** [comment]
Yep seems I forgot to to change a string and the incorrect url was being called to get favorites. I just fixed it in [2022.04.24.1](https://github.com/AplhaSlayer1964/kemono-dl/releases/tag/2022.04.24.1)
